#!/bin/bash

NAME="TorrentLoader"
# NOW=$(date +"%Y-%m-%d_%H-%M-%S")
APPLICATION_DIRECTORY="/home/ivanabramenko/TorrentLoader"
APPLICATION_START=app.js
PIDFILE=/var/run/TorrentLoader.pid
LOGFILE="/home/ivanabramenko/downloads/torrents/log/TorrentLoader.log"


start() {
    echo "Starting $NAME"

    forever --pidFile $PIDFILE --sourceDir $APPLICATION_DIRECTORY \
        -a -l $LOGFILE --minUptime 5000 --spinSleepTime 2000 \
        start $APPLICATION_START
    RETVAL=$?
}

stop() {
    if [ -f $PIDFILE ]; then
        echo "Shutting down $NAME"
        forever stop $APPLICATION_START
        rm -f $PIDFILE
        RETVAL=$?
    else
        echo "$NAME is not running."
        RETVAL=0
    fi
}

restart() {
    echo "Restarting $NAME"
    stop
    start
}

status() {
    echo "Status for $NAME:"
    forever list | grep "$NAME"
    RETVAL=$?
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status
        ;;
    restart)
        restart
        ;;
    *)
        echo "Usage: {start|stop|status|restart}"
        exit 1
        ;;
esac
exit $RETVAL
